<h1>THEME INDEX</h1>
<div class="hero-unit">
    <h1>Welcome to <span class="zf-green">ZeTheme</span></h1>
    <p>Congratulations! You have successfully installed the <a href="https://github.com/ZendExperts/ZeTheme" target="_blank">ZeTheme Module</a>. You are currently running Zend Framework version <?php echo \Zend\Version::VERSION ?>. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.</p>
    <p><a class="btn btn-success btn-large" href="https://github.com/ZendExperts/ZeTheme" target="_blank">Fork ZeTheme Module on GitHub &raquo;</a></p>
  </div>
