<?php

if (empty($this->title)) {
	$this->title = 'WebHemi Admin';
}

echo $this->doctype();
?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle($this->translate($this->title))->setSeparator(' - ')->setAutoEscape(false) ?>
	</head>
	<body>
		<?php echo $this->HeaderBlock; ?>
		<?php echo $this->MenuBlock; ?>
		<div class="container">
			<?php echo $this->content; ?>
		</div> <!-- /container -->
		<?php echo $this->FooterBlock; ?>
	</body>
</html>
