<?php

/** @var $this \Zend\View\Renderer\PhpRenderer */
/** @var $form \WebHemi2\Form\LoginForm */

$form      = $this->loginForm;
$headTitle = $this->headTitle($this->translate($this->headerTitle))->setSeparator(' - ')->setAutoEscape(false);
$css       = $this->headLink()->appendStylesheet('/resources/common/css/reset.css')
                ->appendStylesheet('/resources/theme/' . $this->theme . '/css/login.css');
$js        = $this->headScript()->appendScript('var THEME_NAME = \'' . $this->theme . '\';')
                ->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js')
                ->appendFile('/resources/common/js/common.js')
                ->appendFile('/resources/theme/' . $this->theme . '/js/login.js');
echo $this->doctype();

?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
        <meta name='viewport' content='width=device-width'>
<?php
    echo "\t\t" . $headTitle . PHP_EOL;
    echo "\t\t" . $css . PHP_EOL;
    echo "\t\t" . $js . PHP_EOL;
?>
    </head>
    <body>
        <div id="loginForm">
            <h1>Login to <?php echo $this->siteTitle; ?></h1>
            <?php echo $form; ?>
        </div>
    </body>
</html>
