<?php
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
//$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
//                 ->appendStylesheet($basePath . '/css/style.css')
//                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

//$this->headLink(array(
//            'rel'  => 'shortcut icon',
//            'type' => 'image/vnd.microsoft.icon',
//            'href' => $basePath . '/images/favicon.ico',
//        ));

// HTML5 shim, for IE6-8 support of HTML elements
//$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript',
//    array('conditional' => 'lt IE 9',));

echo $this->doctype();
?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php
		echo $this->headTitle('WebHemi');
		echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
		echo $this->headLink();
		echo $this->headScript()
	?>
	</head>
	<body>
		<h1>SILVER THEME LAYOUT</h1>
<?php if ($this->getIdentity()) : ?>
		<a href="<?php echo $this->url('user'); ?>">My Profile</a> |
		<a href="<?php echo $this->url('user/logout'); ?>">Logout</a>
<?php else : ?>
		<a href="<?php echo $this->url('user/login'); ?>">Login</a>
<?php endif; ?>
		<hr>
		<?php echo $this->content; ?>
		<footer>
			<p>&copy; 2012 by Gixx-web. All rights reserved.</p>
		</footer>
	</body>
</html>
