<h1><?php echo $this->translate('Users') ?></h1>
<p><?php echo $this->translate('Ut convallis, sem sit amet interdum consectetuer, odio augue aliquam leo, nec dapibus tortor nibh sed augue. Integer eu magna sit amet metus fermentum posuere. Morbi sit amet nulla sed dolor elementum imperdiet. Quisque fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque adipiscing eros ut libero. Ut condimentum mi vel tellus. Suspendisse laoreet. Fusce ut est sed dolor gravida convallis. Morbi vitae ante. Vivamus ultrices luctus nunc. Suspendisse et dolor. Etiam dignissim. Proin malesuada adipiscing lacus. Donec metus. Curabitur gravida.'); ?></p>
<a href="<?php echo $this->url('index/control-panel/user/profile'); ?>"><?php echo $this->translate('My Profile'); ?></a>
<hr />

<?php if($this->isAllowed('user-management:user-add')): ?>
<a href="<?php echo $this->url('index/control-panel/user/add'); ?>" class="addUser" style="display:inline-block;text-align: center;">
    <?php
        echo $this->avatar(
            'http://a.dryicons.com/images/icon_sets/classy_icons_set/png/128x128/user_add.png',
            [],
            [
                'style' => 'width:100px;',
                'alt'   => '',
                'title' => $this->translate('Add User')
            ]
        );
    ?><br>
    [<?php echo $this->translate('Add User'); ?>]
</a>
<?php endif; ?>
<?php
/** @var \WebHemi2\Model\User[] $userList */
foreach($userList as $id => $userModel):
    if (
        $userModel->getEnabled()
        || (!$userModel->getEnabled() && $this->isAllowed('user-management:user-enable'))
    ):
        $class = [];
        if (!$userModel->getActive()) {
            $class[] = 'inactive';
        }

        if (!$userModel->getEnabled()) {
            $class[] = 'disabled';
        }

        if ($userModel->getUserId() == $this->getIdentity()->getuserId()) {
            $class[] = 'self';
            $link = $this->url('index/control-panel/user/profile');
        }
        elseif(!$this->isAllowed('user-management:user-view')) {
            $link = '#';
        }
        else {
            $link = $this->url('index/control-panel/user/view', ['userName' => $userModel->getUserName()]);
        }
?>

<a href="<?php echo $link ?>" class="<?php echo implode(' ', $class); ?>" style="display:inline-block;text-align: center;">
    <?php
        echo $this->avatar(
            $userModel->getAvatar(),
            [],
            [
                'style' => 'width:100px;',
                'alt'   => $userModel->getDisplayName(),
                'title' => $userModel->getDisplayName(),
            ]
        );
    ?>
    <?php if (!$userModel->getEnabled()): ?><img src="http://icons.iconarchive.com/icons/visualpharm/must-have/256/Delete-icon.png" style="width:20px;" alt="" /><?php endif; ?>
    <?php if (!$userModel->getActive()): ?><img src="http://cdn1.iconfinder.com/data/icons/devine_icons/Black/PNG/System%20and%20Internet/Times%20and%20Dates.png" style="width:20px;" alt="" /><?php endif; ?>
    <br>
    [<?php echo $userModel->getDisplayName(); ?>]
</a>
<?php
    endif;
endforeach;
?>
