<?php
if (!isset($myProfile)) {
    $myProfile = false;
} else {
    /* @var $userModel \WebHemi2\Model\User */
?>
<a href="<?php echo $this->url('index/user/edit', array('userName' => $userModel->getUserName())) ?>" title="<?php echo $this->translate('Edit profile'); ?>"><?php echo $this->translate('Edit profile'); ?></a>
<?php
}
?>
<div style="width: auto; overflow:hidden; margin-bottom: 10px;">
    <?php
        echo $this->avatar(
            $userModel->getAvatar(), array(), array(
                'style' => 'width: 100px; float: left; padding-right: 16px;'
            )
        );
    ?>
    <h1><?php echo $userModel->getDisplayName(); ?></h1>
    <?php if($headLine = $userModel->getHeadLine()): ?><h2><?php echo $headLine; ?></h2><?php endif; ?>
    <?php if($location = $userModel->getLocation()): ?><h3><?php echo $location; ?></h3><?php endif; ?>
</div>
<table summary="<?php echo $this->translate('Contact Info'); ?>">
    <tbody>
        <tr>
            <td class="email"><?php echo $this->translate('Email'); ?></td>
            <td>
                <?php if($userModel->getDisplayEmail() || $this->isAllowed('user-management:user-edit')): ?>
                <a href="mailto:<?php echo $userModel->getEmail(); ?>"><?php echo $userModel->getEmail(); ?></a>
                <?php else: ?>
                <span><?php echo $this->translate('hidden'); ?></span>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td class="phone"><?php echo $this->translate('Phone'); ?></td>
            <td>
                <?php if($phoneNumber = $userModel->getPhoneNumber()): ?>
                <a href="tel:<?php echo $phoneNumber; ?>"><?php echo $phoneNumber; ?></a>
                <?php else: ?>
                N/A
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td class="im"><?php echo $this->translate('IM'); ?></td>
            <td>
                <?php
                    if($instantMessengerData = $userModel->getInstantMessengers()):
                        $instantMessengerData = @json_decode($instantMessengerData, true);
                        if ($instantMessengerData && is_array($instantMessengerData)):
                            foreach ($instantMessengerData as $imType => $imId):
                ?>
                <?php echo $imId; ?> (<?php echo $imType; ?>)<br />
                <?php
                            endforeach;
                        endif;
                    else:
                        echo 'N/A';
                    endif;
                ?>
            </td>
        </tr>
        <tr>
            <td class="social"><?php echo $this->translate('Social networks'); ?></td>
            <td>
                <?php
                    if($socialNetworkData = $userModel->getSocialNetworks()):
                        $socialNetworkData = @json_decode($socialNetworkData, true);
                        if ($socialNetworkData && is_array($socialNetworkData)):
                            foreach ($socialNetworkData as $snType => $snId):
                ?>
                <span class="<?php echo strtolower($snType); ?>"><?php echo $snType; ?></span> <a href="<?php echo $snId; ?>"><?php echo $snId; ?></a><br />
                <?php
                            endforeach;
                        endif;
                    else:
                        echo 'N/A';
                    endif;
                ?>
            </td>
        </tr>
        <tr>
            <td class="website"><?php echo $this->translate('Websites'); ?></td>
            <td>
                <?php
                    if($webSiteData = $userModel->getWebsites()):
                        $webSiteData = @json_decode($webSiteData, true);
                        if ($webSiteData && is_array($webSiteData)):
                            foreach ($webSiteData as $wsTitle => $url):
                ?>
                <a href="<?php echo $url; ?>"><?php echo $wsTitle; ?></a><br />
                <?php
                            endforeach;
                        endif;
                    else:
                        echo 'N/A';
                    endif;
                ?>
            </td>
        </tr>
    </tbody>
</table>
<?php if ($details = $userModel->getDetails()): ?>
<div class="details"><?php echo $details; ?></div>
<?php endif; ?>
