<h1>Sign In</h1>

<?php

$form = $this->loginForm;
$form->setAttribute('action', '/user/login');
$form->prepare();
echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formRow($form->get('username')) . PHP_EOL;
echo $this->formRow($form->get('password')) . PHP_EOL;
echo $this->formRow($form->get('token')) . PHP_EOL;
echo $this->formRow($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;