<?php

// init
/* @var $form \WebHemi\Form\LoginForm */
$form      = $this->loginForm;
$headTitle = $this->headTitle($this->translate($this->headerTitle))->setSeparator(' - ')->setAutoEscape(false);
$css       = $this->headLink()->appendStylesheet('/wh_application/resources/Admin/style/login.css');
$js        = $this->headScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js')
				->appendFile('/wh_application/resources/Admin/script/script.js');
echo $this->doctype();

?>

<html lang="en">
	<head>
		<meta charset="utf-8">
<?php
	echo "\t\t" . $headTitle . PHP_EOL;
	echo "\t\t" . $css . PHP_EOL;
	echo "\t\t" . $js . PHP_EOL;
?>
	</head>
	<body>
		<div id="loginForm">
			<h1>Login to <?php echo $this->siteTitle; ?></h1>
			<?php echo $form; ?>
		</div> <!-- /container -->
	</body>
</html>
