<h1><?php echo $this->translate('Users') ?></h1>
<p><?php echo $this->translate('Ut convallis, sem sit amet interdum consectetuer, odio augue aliquam leo, nec dapibus tortor nibh sed augue. Integer eu magna sit amet metus fermentum posuere. Morbi sit amet nulla sed dolor elementum imperdiet. Quisque fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque adipiscing eros ut libero. Ut condimentum mi vel tellus. Suspendisse laoreet. Fusce ut est sed dolor gravida convallis. Morbi vitae ante. Vivamus ultrices luctus nunc. Suspendisse et dolor. Etiam dignissim. Proin malesuada adipiscing lacus. Donec metus. Curabitur gravida.'); ?></p>
<a href="<?php echo $this->url('user/profile'); ?>"><?php echo $this->translate('My Profile'); ?></a>
<?php if($this->isAllowed('admin/adduser')): ?>
<a href="<?php echo $this->url('user/new'); ?>"><?php echo $this->translate('Add User'); ?></a>
<?php endif; ?>