<header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
        <!-- Title -->
        <span class="mdl-layout-title"><?php echo $this->sectionTitle; ?></span>
        <!-- Add spacer, to align navigation to the right -->
        <div class="mdl-layout-spacer"></div>
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right">
            <label class="mdl-button mdl-js-button mdl-button--icon"
                   for="fixed-header-drawer-exp">
                <i class="material-icons">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
                <input class="mdl-textfield__input" type="text" name="sample"
                       id="fixed-header-drawer-exp" />
            </div>
        </div>
    </div>
    <!-- Tabs -->
    <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
        <a href="#scroll-tab-1" class="mdl-layout__tab is-active">Tab 1</a>
        <a href="#scroll-tab-2" class="mdl-layout__tab">Tab 2</a>
        <a href="#scroll-tab-3" class="mdl-layout__tab">Tab 3</a>
        <a href="#scroll-tab-4" class="mdl-layout__tab">Tab 4</a>
        <a href="#scroll-tab-5" class="mdl-layout__tab">Tab 5</a>
        <a href="#scroll-tab-6" class="mdl-layout__tab">Tab 6</a>
    </div>
</header>