<nav class="menu">
    <ul>
<?php if($this->isAllowed('admin:index')): ?>
        <li class="dashboard"><a href="<?php echo $this->url('index'); ?>"><span>Dashboard</span></a></li>
<?php endif; ?>
<?php if($this->isAllowed('admin:application')): ?>
        <li class="application"><a href="<?php echo $this->url('index/application'); ?>"><span>Application</span></a></li>
<?php endif; ?>
<?php if($this->isAllowed('admin:control-panel')): ?>
        <li class="control-panel"><a href="<?php echo $this->url('index/control-panel'); ?>"><span>Control Panel</span></a></li>
<?php endif; ?>
<?php if($this->isAllowed('admin:about')): ?>
        <li class="about"><a href="<?php echo $this->url('index/about'); ?>"><span>About</span></a></li>
<?php endif; ?>
    </ul>
</nav>
<nav class="logout">
    <ul>
        <li class="logout"><a href="<?php echo $this->url('index/logout'); ?>"><span>Logout</span></a></li>
    </ul>
</nav>