<?php

if (empty($this->title)) {
    $this->title = 'WebHemi2 Admin';
}
$headTitle = $this->headTitle($this->translate($this->title))->setSeparator(' - ')->setAutoEscape(false);
$css       = $this->headLink()->appendStylesheet('/resources/common/css/reset.css')
                ->appendStylesheet('/resources/theme/default/css/admin.css');
$js        = $this->headScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js')
                ->appendFile('/resources/common/js/script.js');

echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
<?php
    echo "\t\t" . $headTitle . PHP_EOL;
    echo "\t\t" . $css . PHP_EOL;
    echo "\t\t" . $js . PHP_EOL;
?>
    </head>
    <body>
        <?php echo $this->HeaderBlock; ?>
        <?php echo $this->MenuBlock; ?>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->FooterBlock; ?>
    </body>
</html>
