<nav>
    <ul>
        <li><a href="<?php echo $this->url('index'); ?>">Dashboard</a></li>
        <li><a href="<?php echo $this->url('user'); ?>">Users</a></li>
<?php if($this->isAllowed('application')): ?>
        <li><a href="<?php echo $this->url('application'); ?>">Application</a></li>
<?php endif; ?>
<?php if($this->isAllowed('component')): ?>
        <li><a href="<?php echo $this->url('component'); ?>">Components</a></li>
<?php endif; ?>
        <li><a href="<?php echo $this->url('index/about'); ?>">About</a></li>
        <li><a href="<?php echo $this->url('user/logout'); ?>">Logout</a></li>
    </ul>
</nav>