<?php

if (empty($this->title)) {
    $this->title = 'WebHemi2 Admin';
}
$this->headTitle($this->sectionTitle);
$headTitle = $this->headTitle($this->translate($this->title))->setSeparator(' - ')->setAutoEscape(false);
$css       = $this->headLink()->appendStylesheet('/resources/common/css/reset.css')
                ->appendStylesheet('/resources/theme/default/css/admin.css');
$js        = $this->headScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js')
                ->appendFile('/resources/common/js/common.js')
                ->appendFile('/resources/theme/default/js/admin.js');

echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
<?php
    echo "\t\t" . $headTitle . PHP_EOL;
    echo "\t\t" . $css . PHP_EOL;
    echo "\t\t" . $js . PHP_EOL;
?>
    </head>
    <body class="<?php echo $this->sectionClass; ?>">
        <aside>
            <?php echo $this->menuBlock; ?>
        </aside>
        <section>
            <header>
                <h1><?php echo $this->sectionTitle; ?></h1>
            </header>
            <article>
                <header>
                    <?php echo $this->headerBlock; ?>
                </header>
                <div>
                    <?php echo $this->content; ?>
                </div>
                <footer>
                    <?php echo $this->footerBlock; ?>
                </footer>
            </article>
        </section>
    </body>
</html>
