<?php

if (empty($this->title)) {
    $this->title = 'WebHemi2 Admin';
}

$this->headTitle($this->sectionTitle);

$headTitle = $this->headTitle($this->translate($this->title))->setSeparator(' - ')->setAutoEscape(false);

$css       = $this->headLink()
                ->appendStylesheet('/resources/common/css/reset.css')
                ->appendStylesheet('/resources/common/css/library/material.min.css')
                ->appendStylesheet('/resources/theme/default/css/admin.css');

$js        = $this->headScript()->appendScript('var THEME_NAME = \'' . $this->theme . '\';' . PHP_EOL .
                    'var DOMAIN = \'' . APPLICATION_DOMAIN . '\';' . PHP_EOL .
                    'var STATIC_DOMAIN = \'' . APPLICATION_STATIC_DOMAIN . '\';' . PHP_EOL
                )
                ->appendFile('/resources/common/js/library/jquery-2.1.4.min.js')
                ->appendFile('/resources/common/js/library/material.min.js')
                ->appendFile('/resources/common/js/common.js')
                ->appendFile('/resources/theme/default/js/admin.js');

echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width">
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
        <link rel="icon" type="image/x-icon" href="favicon.ico" />
<?php
    echo $headTitle . PHP_EOL;
    echo $css . PHP_EOL;
?>
    </head>
    <body class="<?php echo $this->sectionClass; ?>">
        <aside>
            <?php echo $this->menuBlock; ?>
        </aside>
        <section>
            <header>
                <h1><?php echo $this->sectionTitle; ?></h1>
            </header>
            <article>
                <header>
                    <?php echo $this->headerBlock; ?>
                </header>
                <div>
                    <?php echo $this->content; ?>
                </div>
                <footer>
                    <?php echo $this->footerBlock; ?>
                </footer>
            </article>
        </section>
        <?php
            echo "\t\t" . $js . PHP_EOL;
        ?>
    </body>
</html>
