<?php

if (empty($this->title)) {
    $this->title = 'WebHemi2 Site';
}
$headTitle = $this->headTitle($this->translate($this->title))->setSeparator(' - ')->setAutoEscape(false);
$css       = $this->headLink()->appendStylesheet('/resources/common/css/reset.css')
                ->appendStylesheet('/resources/theme/default/css/website.css');
$js        = $this->headScript()
                ->appendFile('/resources/common/js/jquery-2.1.4.min.js')
                ->appendFile('/resources/common/js/common.js');
echo $this->doctype();
echo $this->theme;
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
<?php
    echo "\t\t" . $headTitle . PHP_EOL;
    echo "\t\t" . $css . PHP_EOL;
    echo "\t\t" . $js . PHP_EOL;
?>
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
        <link rel="icon" type="image/x-icon" href="favicon.ico" />
    </head>
    <body>
        <div class="container">
            <h1>HEMI WEBSITE LAYOUT</h1>
<?php if ($this->getIdentity()) : ?>
            <a href="<?php echo $this->url('index/user/profile'); ?>">My Profile</a> |
            <a href="<?php echo $this->url('index/logout'); ?>">Logout</a>
<?php else : ?>
            <a href="<?php echo $this->url('index/login'); ?>">Login</a>
<?php endif; ?>
            <hr>
            <aside>
                <?php echo $this->menuBlock; ?>
            </aside>
            <section>
                <header>
                    <h1><?php echo $this->sectionTitle; ?></h1>
                </header>
                <article>
                    <header>
                        <?php echo $this->headerBlock; ?>
                    </header>
                    <div>
                        <?php echo $this->content; ?>
                    </div>
                    <footer>
                        <?php echo $this->footerBlock; ?>
                    </footer>
                </article>
            </section>
        </div> <!-- /container -->
    </body>
</html>
