<?php

/** @var $this \Zend\View\Renderer\PhpRenderer */
/** @var $form \WebHemi2\Form\LoginForm */

$form      = $this->loginForm;
$headTitle = $this->headTitle($this->translate($this->headerTitle))->setSeparator(' - ')->setAutoEscape(false);

$this->headLink()
    ->appendStylesheet('/resources/common/css/reset.css');
$this->headScript()
    ->appendScript('var THEME_NAME = \'' . (
            file_exists(APPLICATION_MODULE_PATH . '/resources/themes/' . $this->theme . '/static/css/login.css')
                ? $this->theme
                : 'default'
        ) . '\';' . PHP_EOL .
        'var DOMAIN = \'' . APPLICATION_DOMAIN . '\';' . PHP_EOL .
        'var STATIC_DOMAIN = \'' . APPLICATION_STATIC_DOMAIN . '\';' . PHP_EOL
    )
    ->appendFile('http://code.jquery.com/jquery-2.1.4.min.js')
    ->appendFile('/resources/common/js/plugins/jquery.form.min.js')
    ->appendFile('/resources/common/js/common.js');

if ($this->themeSettings['mdl_enabled']) {
    $this->headLink()
        ->appendStylesheet('https://storage.googleapis.com/code.getmdl.io/1.0.2/material.' .
            $this->themeSettings['mdl_primary'] . '-' . $this->themeSettings['mdl_accent'] . '.min.css'
        )
        ->appendStylesheet('https://fonts.googleapis.com/icon?family=Material+Icons');
    $this->headScript()
        ->appendFile('https://storage.googleapis.com/code.getmdl.io/1.0.2/material.min.js');
}

if (file_exists(APPLICATION_MODULE_PATH . '/resources/themes/' . $this->theme . '/static/css/login.css')) {
    $this->headLink()
        ->appendStylesheet('/resources/theme/' . $this->theme . '/css/login.css');

    if (file_exists(APPLICATION_MODULE_PATH . '/resources/themes/' . $this->theme . '/static/js/login.js')) {
        $this->headScript()
            ->appendFile('/resources/theme/' . $this->theme . '/js/login.js');
    }
} else {
    $this->headLink()
        ->appendStylesheet('/resources/theme/default/css/login.css');
    $this->headScript()
        ->appendFile('/resources/theme/default/js/login.js');
}

echo $this->doctype();

?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php
    echo "\t\t" . $headTitle . PHP_EOL;
    echo "\t\t" . $this->headLink() . PHP_EOL;
?>
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
        <link rel="icon" type="image/x-icon" href="favicon.ico" />
    </head>
    <body>
        <div id="loginForm">
            <h1><?php echo $this->loginTitle; ?></h1>
            <?php echo $form; ?>
        </div>
        <?php
            echo "\t\t" . $this->headScript() . PHP_EOL;
        ?>
    </body>
</html>
